spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem://localhost/~/readinglist;MVCC=TRUE;DB_CLOSE_ON_EXIT=FALSE

  jpa:
    show-sql: true
    properties:
      format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect